# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pavelstanlley', '0012_auto_20160301_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, upload_to=b'post_images'),
        ),
    ]
