# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pavelstanlley', '0016_post_edit_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostPictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'post_images', verbose_name=b'image')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='picture',
        ),
        migrations.AddField(
            model_name='postpictures',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pavelstanlley.Post'),
        ),
    ]
