# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pavelstanlley', '0019_auto_20160313_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postpictures',
            name='post',
        ),
        migrations.AddField(
            model_name='postpictures',
            name='post',
            field=models.ManyToManyField(default=3, to='pavelstanlley.Post'),
        ),
    ]
