# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 02:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pavelstanlley', '0022_auto_20160313_0246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='photo',
            new_name='picture',
        ),
    ]
