# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pavelstanlley', '0027_auto_20160314_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paczki',
            name='p',
            field=models.IntegerField(),
        ),
    ]
