# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pavelstanlley', '0034_auto_20160325_0324'),
    ]

    operations = [
        migrations.DeleteModel(
            name='archive',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name_surname',
            new_name='imie',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='temat',
        ),
    ]
