# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pavelstanlley', '0035_auto_20160408_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=120)),
                ('projectimage', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('startproject', models.DateTimeField(blank=True, null=True)),
                ('endproject', models.DateTimeField(blank=True, null=True)),
                ('otherauthors', models.CharField(max_length=120)),
                ('descriptionproject', models.TextField()),
            ],
        ),
    ]
