# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 23:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pavelstanlley', '0036_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='endproject',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 10, 23, 12, 15, 227477, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='startproject',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 10, 23, 12, 31, 667409, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
