# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 00:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pavelstanlley', '0040_auto_20160412_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 4, 12, 0, 19, 4, 720084, tzinfo=utc), unique=True),
            preserve_default=False,
        ),
    ]
