# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 23:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pavelstanlley', '0047_auto_20160412_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 13, 23, 49, 3, 656975, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
