# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pavelstanlley', '0051_remove_projects_projectimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('views', models.IntegerField(default=0)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.RemoveField(
            model_name='postpictures',
            name='post',
        ),
        migrations.DeleteModel(
            name='PostPictures',
        ),
    ]
