# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 16:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pavelstanlley', '0053_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='author',
            field=models.CharField(default=datetime.datetime(2016, 4, 19, 16, 53, 26, 218061, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
