# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pavelstanlley', '0011_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
