# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pavelstanlley', '0015_contact_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edit_pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
