# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 00:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pavelstanlley', '0018_auto_20160312_0206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postpictures',
            old_name='image',
            new_name='picture',
        ),
        migrations.AlterField(
            model_name='postpictures',
            name='post',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='pavelstanlley.Post'),
        ),
    ]
