# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 01:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pavelstanlley', '0021_auto_20160313_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=b'post_images')),
            ],
        ),
        migrations.RemoveField(
            model_name='postpictures',
            name='post',
        ),
        migrations.AddField(
            model_name='postpictures',
            name='post',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='pavelstanlley.Post'),
            preserve_default=False,
        ),
    ]
