# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pavelstanlley', '0024_photos_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paczki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paczki', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='User_profile',
        ),
    ]
