# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pavelstanlley', '0026_auto_20160314_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paczki',
            old_name='paczki',
            new_name='p',
        ),
    ]
