# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 00:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pavelstanlley', '0029_auto_20160314_2243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paczki',
        ),
    ]
