# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 01:19
from __future__ import unicode_literals


import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pavelstanlley', '0030_delete_paczki'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='post',
        ),

        migrations.AddField(
            model_name='postpictures',
            name='caption',
            field=models.CharField(default=datetime.datetime(2016, 3, 15, 1, 19, 47, 135236, tzinfo=utc), max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postpictures',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pictures', to='pavelstanlley.Post'),
        ),
        migrations.DeleteModel(
            name='Photos',
        ),
    ]
