# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 02:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pavelstanlley', '0033_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='month_choices',
            field=models.DateTimeField(choices=[(datetime.datetime(2016, 2, 23, 3, 24, 52, 19406), b'Styczen'), (datetime.datetime(2016, 1, 23, 3, 24, 52, 19406), b'Luty'), (datetime.datetime(2015, 12, 23, 3, 24, 52, 19406), b'Marzec'), (datetime.datetime(2015, 11, 25, 3, 24, 52, 19406), b'Kwiecien')], default=datetime.datetime(2016, 2, 23, 3, 24, 52, 19406)),
        ),
    ]
