# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 02:32
from __future__ import unicode_literals

import datetime
from django.db import migrations
from django.utils.timezone import utc



class Migration(migrations.Migration):

    dependencies = [
        ('pavelstanlley', '0037_auto_20160411_0112'),
    ]


