# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pavelstanlley', '0039_projects_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='otherauthors',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
