# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 14:16
from __future__ import unicode_literals


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pavelstanlley', '0041_projects_slug'),
    ]

    operations = [

        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(),
        ),

    ]
