# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pavelstanlley', '0042_auto_20160412_1616'),
    ]


