# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pavelstanlley', '0049_auto_20160414_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[(b'koncepcja', 'pomys\u0142 projektu'), ('w trakcie realizacji', 'W trakcie realizacji'), ('przerwano', 'Projekt przerwano'), ('zako\u0144czono', 'Projekt zako\u0144czono')], default=b'koncepcja', max_length=50),
        ),
    ]
